- Generated specification for integration testing of TaskService: $ grails create-integration-test com.tekdays.TaskService
- I do not know why, bu I cannot run this integration test successfully from IDEA. It fails with the following exception:

java.lang.IllegalStateException: Method on class [com.tekdays.TekUser] was used outside of a Grails application. If running in the context of a test using the mocking API or bootstrap Grails correctly.
	at com.tekdays.TaskServiceSpec.setup(TaskServiceSpec.groovy:15)

This might be an issue with Grails version which need to updated. However, I am not going to update Grails, therefore, just use command:
$ grails test-app

After that, open test report (index.html) and make sure the test in TaskServiceSpec passed successfully.

Chapter 6. Getting Things Done, p. 100